# Use root/example as user/password credentials
version: '3'

services:
    mysqldb:
        image: mysql
        container_name: "teste"
        volumes:
            - ./.data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: root
            MYSQL_PASSWORD: 'root'
            DATABASE_HOST: 127.0.0.1
        ports:
            - "3306:3306"
volumes:
    data: