# Generated by Django 3.0 on 2020-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_one', models.FloatField(db_column='measure_one', null=True)),
                ('measure_two', models.FloatField(db_column='measure_two', null=True)),
                ('measure_three', models.FloatField(db_column='measure_three', null=True)),
                ('measure_four', models.FloatField(db_column='measure_four', null=True)),
                ('predicted_value', models.FloatField(db_column='predicted_value', null=True)),
                ('weekday', models.FloatField(db_column='weekday', null=True)),
                ('weekend', models.FloatField(db_column='weekend', null=True)),
                ('season', models.FloatField(db_column='season', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'measures',
            },
        ),
    ]
