# Generated by Django 3.0 on 2020-07-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsl_layer', '0002_auto_20200723_0216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measures',
            new_name='Measure',
        ),
    ]
