# Generated by Django 3.0 on 2020-10-24 17:15

from django.db import migrations, models
import djongo.models.fields
import dsl_broker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityModel',
            fields=[
                ('entity_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('model', djongo.models.fields.EmbeddedField(default=None, model_container=dsl_broker.models.Model)),
                ('Subscription', djongo.models.fields.EmbeddedField(default=None, model_container=dsl_broker.models.Subscription)),
            ],
        ),
    ]
